### ISSUE TITLE
Create database plugins for Teeid and Calcite

### ISSUE THREAD

**Issue by sualeh** [schemacrawler/SchemaCrawler-Database-Plugins#10]
### Feature Request

Create database plugins for Teeid and Calcite in [schemacrawler/SchemaCrawler-Database-Plugins](https://github.com/schemacrawler/SchemaCrawler-Database-Plugins). See https://github.com/schemacrawler/SchemaCrawler/issues/645 @GavinRay97

**Comment by sualeh** [comment]
Released Teiid plugin. SchemaCrawler cannot support Calcite.

**Comment by sualeh** [comment]
@GavinRay97 - I have released the SchemaCrawler Teiid plugin - you can simply add this jar to your classpath.

**Comment by GavinRay97** [comment]
Thank you!!
