### ISSUE TITLE
Allowing Driver to be specified as an input parameter instead of using DriverManager.getDriver (for Sybase use case)

### ISSUE THREAD

**Issue by sualeh** [schemacrawler/SchemaCrawler-Database-Plugins#3]
See https://github.com/schemacrawler/SchemaCrawler/issues/323 for background.
Modify the Sybase `DatabaseServerType` to take a third constructor parameter for the driver class name.

**Comment by schemacrawler** [comment]
@shantstepanian -

**Comment by shantstepanian** [comment]
Thanks; I will need a few days, but will let you know when I have it

**Comment by sualeh** [comment]
@shantstepanian - please fix this issue too. Thanks.

**Comment by sualeh** [comment]
Closing due to no action.
